# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: population.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='population.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10population.proto\"\xff\x01\n\nPopulation\x12\x11\n\tdimension\x18\x01 \x01(\x05\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0c\n\x04mean\x18\x03 \x03(\x01\x12\x12\n\ncovariance\x18\x04 \x03(\x01\x12\x32\n\x0e\x66itnessSummary\x18\x05 \x01(\x0b\x32\x1a.Population.FitnessSummary\x12\x12\n\npopulation\x18\x06 \x03(\x01\x12\x0f\n\x07\x66itness\x18\x07 \x03(\x01\x1aU\n\x0e\x46itnessSummary\x12\x0e\n\x06median\x18\x01 \x01(\x01\x12\x0c\n\x04mean\x18\x02 \x01(\x01\x12\x0b\n\x03min\x18\x03 \x01(\x01\x12\x0b\n\x03max\x18\x04 \x01(\x01\x12\x0b\n\x03std\x18\x05 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POPULATION_FITNESSSUMMARY = _descriptor.Descriptor(
  name='FitnessSummary',
  full_name='Population.FitnessSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='median', full_name='Population.FitnessSummary.median', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean', full_name='Population.FitnessSummary.mean', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='Population.FitnessSummary.min', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='Population.FitnessSummary.max', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='std', full_name='Population.FitnessSummary.std', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=276,
)

_POPULATION = _descriptor.Descriptor(
  name='Population',
  full_name='Population',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='Population.dimension', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='Population.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean', full_name='Population.mean', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='Population.covariance', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fitnessSummary', full_name='Population.fitnessSummary', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='population', full_name='Population.population', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='Population.fitness', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_POPULATION_FITNESSSUMMARY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=276,
)

_POPULATION_FITNESSSUMMARY.containing_type = _POPULATION
_POPULATION.fields_by_name['fitnessSummary'].message_type = _POPULATION_FITNESSSUMMARY
DESCRIPTOR.message_types_by_name['Population'] = _POPULATION

Population = _reflection.GeneratedProtocolMessageType('Population', (_message.Message,), dict(

  FitnessSummary = _reflection.GeneratedProtocolMessageType('FitnessSummary', (_message.Message,), dict(
    DESCRIPTOR = _POPULATION_FITNESSSUMMARY,
    __module__ = 'population_pb2'
    # @@protoc_insertion_point(class_scope:Population.FitnessSummary)
    ))
  ,
  DESCRIPTOR = _POPULATION,
  __module__ = 'population_pb2'
  # @@protoc_insertion_point(class_scope:Population)
  ))
_sym_db.RegisterMessage(Population)
_sym_db.RegisterMessage(Population.FitnessSummary)


# @@protoc_insertion_point(module_scope)
