# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/problem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/problem.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14protos/problem.proto\"o\n\x07Problem\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12\x1e\n\x06params\x18\x03 \x03(\x0b\x32\x0e.Problem.param\x1a#\n\x05param\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x03(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROBLEM_PARAM = _descriptor.Descriptor(
  name='param',
  full_name='Problem.param',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Problem.param.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Problem.param.value', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=135,
)

_PROBLEM = _descriptor.Descriptor(
  name='Problem',
  full_name='Problem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Problem.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dimension', full_name='Problem.dimension', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='Problem.params', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROBLEM_PARAM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=135,
)

_PROBLEM_PARAM.containing_type = _PROBLEM
_PROBLEM.fields_by_name['params'].message_type = _PROBLEM_PARAM
DESCRIPTOR.message_types_by_name['Problem'] = _PROBLEM

Problem = _reflection.GeneratedProtocolMessageType('Problem', (_message.Message,), dict(

  param = _reflection.GeneratedProtocolMessageType('param', (_message.Message,), dict(
    DESCRIPTOR = _PROBLEM_PARAM,
    __module__ = 'protos.problem_pb2'
    # @@protoc_insertion_point(class_scope:Problem.param)
    ))
  ,
  DESCRIPTOR = _PROBLEM,
  __module__ = 'protos.problem_pb2'
  # @@protoc_insertion_point(class_scope:Problem)
  ))
_sym_db.RegisterMessage(Problem)
_sym_db.RegisterMessage(Problem.param)


# @@protoc_insertion_point(module_scope)
